language: node_js
node_js:
  - "6.9"

branches:
  only:
    - master
    - develop

before_script:
  - npm install -g gulp

script:
  - gulp bundle

notifications:
  email:
    on_failure: change
    on_success: change
